# Site
repository: rdiazpas/modern-resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Raul Diaz Pascua
title: Senior Cloud Architect
email: rauldp2006@gmail.com
website: https://rdiazpas.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: RaulDiazPascua
github_username:  rdiazpas
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: raul-diaz-pascua
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Raul and I'm a senior cloud architect. As well as designing cloud solutions I'm technical passionated. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Azure</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/rdiazpas
        # link_text: Project Website
        additional_links:
          - title:  rdiazpas/cv
            icon: fab fa-github
            url: https://rdiazpas.github.io/cv
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is my first personal project to practice github pages.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of learning <mark>Github-pages</mark>. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Accenture
        link: https://www.accenture.com/
        link_text: Accenture.com
        sub_title: Senior Cloud Architect
        caption: October 2006 - Present
        quote: >
          Multiple projects and roles as Cloud Architect and System administrator.
        description: | # this will include new lines to allow paragraphs
          Every company needs its systems properly administered and designed, I play my part to ensure the success.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UOC University (Universitat Oberta de Catalunya)
        caption: 2017 - 2020
        sub_title: BSc Computer Science
        quote: >
          Founded in 1994, UOC is an internationally recognised online university with a community of over 60,000 students. The mission of the Universitat Oberta de Catalunya (UOC) is to provide people with lifelong learning and education opportunities. The aim is to help individuals meet their learning needs and provide them with full access to knowledge, above and beyond the usual scheduling and location constraints.
        description: | # this will include new lines to allow paragraphs
          During my time at UOC to upgrade my previous university studies to the new Computer Science study program, I was able to learnt most of my dev skills rounding out my professional skills. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance. 
          
          My professional role is specially related with system administration and cloud solution design skills. I have developed teamwork and working to tight deadlines skills.

          I found a balance between my professional role, study and personal life.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Basketball
      - Family
      - Gaming
      - [Real Madrid](https://www.youtube.com/watch?v=muGyJEu12A8)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
#remote_theme: sproogen/resume-theme
remote_theme: rdiazpas/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
